plugins { id 'com.android.application' }
android {
    namespace 'com.hmacademy.offline'
    compileSdk 35
    defaultConfig {
        applicationId 'com.hmacademy.offline'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    buildTypes { release { minifyEnabled false } }
}
dependencies { implementation 'androidx.documentfile:documentfile:1.0.1' }