const CACHE="hm-academy-offline-v2";
self.addEventListener("install",e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(["/","/offline/OFFLINE-VIDEO.html"])));self.skipWaiting()});
self.addEventListener("activate",e=>e.waitUntil(self.clients.claim()));
function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8"}})}
const supabaseModule='export function createClient(){const session={user:{id:"offline-user",email:"offline@local.hm"},access_token:"offline-session",offline:true};const auth={getSession:async()=>({data:{session},error:null}),getUser:async()=>({data:{user:session.user},error:null}),signInWithPassword:async()=>({data:{session,user:session.user},error:null}),signUp:async()=>({data:{session,user:session.user},error:null}),resetPasswordForEmail:async()=>({data:{},error:null}),updateUser:async()=>({data:{user:session.user},error:null}),signOut:async()=>({error:null}),onAuthStateChange:cb=>{setTimeout(()=>{try{cb("SIGNED_IN",session)}catch(e){}},0);return {data:{subscription:{unsubscribe(){}}}}}};const chain={select(){return chain},eq(){return chain},order(){return chain},limit(){return chain},single:async()=>({data:null,error:null}),maybeSingle:async()=>({data:null,error:null}),insert:async()=>({data:null,error:null}),upsert:async()=>({data:null,error:null}),update(){return chain},delete(){return chain}};return {auth,from:()=>chain,rpc:async()=>({data:null,error:null}),storage:{from:()=>({})}}}';
const supabaseClassic='window.supabase=window.supabase||{createClient:function(){return {auth:{getSession:async()=>({data:{session:null},error:null}),signOut:async()=>({error:null})}}}};';
self.addEventListener("fetch",event=>{const u=new URL(event.request.url);
if(u.hostname==="fonts.googleapis.com"||u.hostname==="fonts.gstatic.com"){event.respondWith(new Response("",{status:200,headers:{"Content-Type":"text/css"}}));return}
if(u.hostname==="esm.sh"&&u.pathname.startsWith("/@supabase/supabase-js")){event.respondWith(new Response(supabaseModule,{status:200,headers:{"Content-Type":"text/javascript; charset=utf-8"}}));return}
if(u.hostname==="cdn.jsdelivr.net"&&u.pathname.includes("@supabase/supabase-js")){event.respondWith(new Response(supabaseClassic,{status:200,headers:{"Content-Type":"text/javascript; charset=utf-8"}}));return}
if(u.hostname.endsWith(".supabase.co")){event.respondWith(json({data:null,error:{message:"HM Academy Offline Mode: remote service unavailable."}}));return}
if(u.hostname==="www.youtube.com"||u.hostname==="youtube.com"||u.hostname==="m.youtube.com"){event.respondWith(Response.redirect(new URL("/offline/OFFLINE-VIDEO.html?source="+encodeURIComponent(u.href),self.location.origin)));return}
if(u.hostname==="cdnjs.cloudflare.com"){event.respondWith(new Response("",{status:200,headers:{"Content-Type":"text/javascript"}}));return}
if(u.origin===self.location.origin){event.respondWith(caches.match(event.request).then(c=>c||fetch(event.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(CACHE).then(x=>x.put(event.request,copy)).catch(()=>{})}return r}).catch(()=>Response.error())))}});
