from pathlib import Path

p = Path('annual-revision-stage.html')
s = p.read_text(encoding='utf-8')

start = s.find('function score(arr,id){')
if start < 0:
    raise SystemExit('Could not locate score()')
end = s.find('function lockScreen(){', start)
if end < 0:
    raise SystemExit('Could not locate lockScreen()')

fn = r'''function questionForBox(arr,box,i){const id=String(box.dataset.questionId||'');if(id){const exact=arr.find(q=>String(q?.id||'')===id);if(exact)return exact}const input=box.querySelector('input[name]');const name=String(input?.name||'');const m=name.match(/(?:^|[-_])([DPF]\d+)$/);const questionId=m?m[1]:'';if(questionId){const exact=arr.find(q=>String(q?.id||'')===questionId);if(exact)return exact}return {};}
function explainQuestion(q){if(q?.explanation||q?.reason||q?.feedback||q?.why)return q.explanation||q.reason||q.feedback||q.why;const text=String(q?.q||q?.question||'').trim(),opts=Array.isArray(q?.options)?q.options.map(x=>String(x??'')):[],answer=opts[q?.answer]??q?.answer,a=String(answer??'').trim(),low=(text+' '+opts.join(' ')+' '+a).toLowerCase();const subject=(text.match(/^(Je|J'|Tu|Il|Elle|On|Nous|Vous|Ils|Elles)\b/i)||[])[1]?.replace("J'",'Je');const etre={Je:'suis',Tu:'es',Il:'est',Elle:'est',On:'est',Nous:'sommes',Vous:'êtes',Ils:'sont',Elles:'sont'};const avoir={Je:'ai',Tu:'as',Il:'a',Elle:'a',On:'a',Nous:'avons',Vous:'avez',Ils:'ont',Elles:'ont'};const aller={Je:'vais',Tu:'vas',Il:'va',Elle:'va',On:'va',Nous:'allons',Vous:'allez',Ils:'vont',Elles:'vont'};const vivre={Je:'vis',Tu:'vis',Il:'vit',Elle:'vit',On:'vit',Nous:'vivons',Vous:'vivez',Ils:'vivent'};if(subject&&etre[subject]===a)return 'الفاعل هو «'+subject+'»، وتصريف الفعل être في المضارع مع هذا الضمير هو «'+a+'». لذلك نختار «'+a+'».';if(subject&&avoir[subject]===a)return 'الفاعل هو «'+subject+'»، وتصريف الفعل avoir في المضارع مع هذا الضمير هو «'+a+'». لذلك نختار «'+a+'».';if(subject&&aller[subject]===a)return 'الفاعل هو «'+subject+'»، وتصريف الفعل aller في المضارع معه هو «'+a+'». لذلك نختار «'+a+'».';if(subject&&vivre[subject]===a)return 'الفاعل هو «'+subject+'»، وتصريف الفعل vivre في المضارع معه هو «'+a+'». لذلك نختار «'+a+'».';
const firstPerson=(subject==='Je');if(firstPerson&&/^(ai|suis|vais|vis)$/.test(a))return 'مع الضمير «Je» نستخدم تصريف المتكلم المفرد المناسب للفعل في السؤال، وهو «'+a+'».';
if(/\b(n'|ne\b).+\bpas\b/i.test(text)||/\bne\b.*\bpas\b/i.test(text)){if(['de',"d'",'d’'].includes(a))return 'الجملة منفية وتستخدم avoir؛ وبعد نفي avoir تتحول أداة التنكير أو الجمع إلى «de/d’». لذلك تكون «'+a+'».';return 'في النفي نضع «ne/n’» قبل الفعل و«pas» بعده؛ والإجابة الصحيحة هي «'+a+'» لأنها تكمل تركيب النفي في الجملة.';}
const nationality=/italien|italienne|français|francais|française|francaise|anglais|anglaise|égyptien|egyptien|égyptienne|egyptienne|espagnol|espagnole|allemand|allemande|marocain|marocaine|tunisien|tunisienne|japonais|japonaise|chinois|chinoise|américain|americaine|américaine|canadien|canadienne/i;if(nationality.test(low)){const feminine=/(elle\b|femme\b|fille\b|féminin|féminine|مؤنث)/i.test(text);const plural=/(ils\b|elles\b|hommes\b|femmes\b|pluriel|جمع)/i.test(text);if(feminine)return '«'+a+'» صفة جنسية، والصفة في الفرنسية تتوافق مع جنس الشخص. لأن الفاعل مؤنث مفرد، نستخدم صيغة المؤنث المفرد «'+a+'».';if(plural)return '«'+a+'» صفة جنسية، والصفة في الفرنسية تتوافق مع الجنس والعدد؛ ولأن الفاعل جمع نستخدم صيغة الجمع المناسبة «'+a+'».';return '«'+a+'» صفة جنسية، وتأتي هنا بصيغة المذكر المفرد لأنها توافق الفاعل المذكر المفرد في السؤال.';}
const articleNouns={une:/\b(robe|jupe|chemise|cravate|ceinture|trousse|gomme|pomme|carotte|maison|classe|table|chaussure|chaussette|veste|école|ecole|voiture|bibliothèque|bibliotheque)\b/i,un:/\b(livre|cahier|stylo|crayon|pantalon|pull|costume|nez|frère|frere|père|pere|garçon|garcon|club|stade|cinéma|cinema)\b/i};if(['un','une','des'].includes(a)){if(a==='une'&&articleNouns.une.test(text))return 'الاسم «'+(text.match(articleNouns.une)||[])[1]+'» مؤنث مفرد، لذلك نستخدم أداة التنكير «une».';if(a==='un'&&articleNouns.un.test(text))return 'الاسم «'+(text.match(articleNouns.un)||[])[1]+'» مذكر مفرد، لذلك نستخدم أداة التنكير «un».';if(a==='des'&&/\b(chaussures|gants|livres|chemises|jupes|pantalons|stylos|crayons)\b/i.test(text))return 'الاسم في السؤال جمع، لذلك نستخدم أداة التنكير «des».';}
if(['du','de la','de l’',"de l'",'au','à la','à l’',"à l'"].includes(a)){if(a==='au')return '«au» ناتجة عن دمج حرف الجر «à» مع أداة التعريف «le»، لذلك تناسب الاسم المذكر المفرد في هذا التركيب.';if(a==='du')return '«du» ناتجة عن دمج «de + le»، لذلك تناسب الاسم المذكر المفرد في هذا التركيب.';if(a==='de la')return 'الاسم مؤنث مفرد، لذلك نستخدم أداة التجزئة «de la».';if(/l['’]/.test(a))return 'الاسم يبدأ بحرف متحرك، لذلك نستخدم الصيغة المختصرة «'+a+'».';if(a==='à la')return 'الاسم مؤنث مفرد، لذلك نستخدم «à la» مع حرف الجر «à».';}
const color=/\b(rouge|jaune|rose|orange|marron|noir|noire|bleu|bleue|vert|verte|gris|grise|blanc|blanche|violet|violette)\b/i;if(color.test(low)){if(/\b(la|une)\b/i.test(text)&&a)return 'الاسم مؤنث مفرد، واللون صفة تتوافق معه في الجنس؛ لذلك نستخدم الصيغة المؤنثة المفردة «'+a+'».';if(/\b(les|des)\b/i.test(text)&&a)return 'الاسم جمع، واللون صفة تتوافق معه في العدد؛ لذلك نستخدم صيغة الجمع «'+a+'».';return 'اللون صفة، والصفة يجب أن تتوافق مع الاسم الموصوف في الجنس والعدد؛ لذلك نستخدم «'+a+'».';}
if(/gros|grosse|vieux|vieille|grand|grande|petit|petite|long|longue|court|courte|fort|forte|maigre|jeune/i.test(low)){if(/féminin|feminin|féminine|مؤنث/i.test(text))return 'السؤال يطلب صيغة المؤنث. في الفرنسية تتغير الصفة لتوافق الاسم المؤنث؛ لذلك نستخدم «'+a+'».';if(/pluriel|جمع/i.test(text))return 'السؤال يطلب صيغة الجمع، لذلك تتوافق الصفة مع الاسم في العدد وتأتي هنا «'+a+'».';if(/\bElle\b/i.test(text))return 'الفاعل «Elle» مؤنث مفرد، لذلك يجب أن تأتي الصفة في المؤنث المفرد، وهي «'+a+'».';if(/\bIl\b/i.test(text))return 'الفاعل «Il» مذكر مفرد، لذلك يجب أن تأتي الصفة في المذكر المفرد، وهي «'+a+'».';if(/\bElles\b/i.test(text))return 'الفاعل «Elles» مؤنث جمع، لذلك يجب أن تأتي الصفة في المؤنث الجمع، وهي «'+a+'».';if(/\bIls\b/i.test(text))return 'الفاعل «Ils» مذكر جمع، لذلك يجب أن تأتي الصفة في المذكر الجمع، وهي «'+a+'».';}
if(/-er\b|parle|aime|joue|habite|chante|regarde|travaille/i.test(low)){const er={Je:'e',Tu:'es',Il:'e',Elle:'e',On:'e',Nous:'ons',Vous:'ez',Ils:'ent',Elles:'ent'};if(subject&&er[subject]&&new RegExp(er[subject]+'$','i').test(a))return 'الفعل من أفعال المجموعة الأولى (-er)، وتصريفه مع «'+subject+'» يأخذ النهاية «-'+er[subject]+'». لذلك نستخدم «'+a+'».';}
if(/avoir|âge|ans|treize|douze|onze|quatorze|quinze|seize|dix|âge/i.test(low)&&['ai','as','a','avons','avez','ont'].includes(a))return 'السؤال يستخدم الفعل avoir، وتصريفه يجب أن يطابق الضمير الفاعل؛ لذلك «'+a+'» هي الصيغة المناسبة.';
if(/être|suis|es|est|sommes|êtes|sont/i.test(low)&&['suis','es','est','sommes','êtes','sont'].includes(a))return 'السؤال يستخدم الفعل être، وتصريفه يجب أن يطابق الضمير الفاعل؛ لذلك «'+a+'» هي الصيغة المناسبة.';
if(/aller|vais|vas|va|allons|allez|vont/i.test(low)&&['vais','vas','va','allons','allez','vont'].includes(a))return 'السؤال يستخدم الفعل aller، وتصريفه يجب أن يطابق الضمير الفاعل؛ لذلك «'+a+'» هي الصيغة المناسبة.';
if(/vivre|vis|vit|vivons|vivez|vivent/i.test(low)&&['vis','vit','vivons','vivez','vivent'].includes(a))return 'السؤال يستخدم الفعل vivre، وتصريفه يجب أن يطابق الضمير الفاعل؛ لذلك «'+a+'» هي الصيغة المناسبة.';
if(/quel|quelle|quels|quelles/i.test(text)){if(/^quelle$/i.test(a))return '«Quelle» تُستخدم مع اسم مؤنث مفرد؛ لذلك تناسب الاسم المؤنث المفرد في السؤال.';if(/^quel$/i.test(a))return '«Quel» تُستخدم مع اسم مذكر مفرد؛ لذلك تناسب الاسم المذكر المفرد في السؤال.';if(/^quels$/i.test(a))return '«Quels» تُستخدم مع اسم مذكر جمع؛ لذلك تناسب الاسم المذكر الجمع في السؤال.';if(/^quelles$/i.test(a))return '«Quelles» تُستخدم مع اسم مؤنث جمع؛ لذلك تناسب الاسم المؤنث الجمع في السؤال.';}
if(/ce|cet|cette|ces/i.test(low)&&/^(ce|cet|cette|ces)$/i.test(a))return 'أداة الإشارة يجب أن تتوافق مع الاسم في الجنس والعدد؛ لذلك «'+a+'» هي الصيغة الموافقة للاسم في السؤال.';
if(/mon|ma|mes|ton|ta|tes|son|sa|ses/i.test(low)&&/^(mon|ma|mes|ton|ta|tes|son|sa|ses)$/i.test(a))return 'أداة الملكية تتوافق مع الاسم المملوك في الجنس والعدد؛ لذلك «'+a+'» هي الصيغة المناسبة للاسم في السؤال.';
return 'الإجابة «'+a+'» صحيحة لأنها تطابق القاعدة النحوية التي يختبرها تركيب السؤال.';}
function grade(arr,id,resultId){const root=$(id),out=$(resultId);let n=0,total=arr.length;root.querySelectorAll('.q').forEach(box=>{const q=questionForBox(arr,box,0),selected=box.querySelector('input:checked');if(!q.id)return;const correct=!!selected&&Number(selected.value)===Number(q.answer);box.querySelectorAll('.answer-feedback').forEach(x=>x.remove());box.querySelectorAll('.option').forEach(x=>x.classList.remove('is-correct','is-wrong'));if(selected)selected.closest('.option')?.classList.add(correct?'is-correct':'is-wrong');if(correct){n++;return}const opts=Array.isArray(q.options)?q.options:[],answer=opts[q.answer]??q.answer,reason=explainQuestion(q),div=document.createElement('div');div.className='answer-feedback';div.innerHTML='<div class="feedback-title">'+(selected?'❌ إجابتك غير صحيحة':'⚠️ لم تتم الإجابة')+'</div><div><b>✅ الإجابة الصحيحة:</b> '+esc(answer)+'</div><div><b>💡 لماذا؟</b> '+esc(reason)+'</div>';box.appendChild(div)});const pct=total?Math.round(n/total*100):0;out.innerHTML='<div class="result"><b>النتيجة: '+n+' / '+total+' ('+pct+'%)</b><br>كل تصحيح يعرض سببًا مرتبطًا بتركيب السؤال وقاعدته، مع منع خلط الأسئلة بين الصفوف.</div>';return n}
function score(arr,id){let n=0;arr.forEach((q,i)=>{const x=document.querySelector('input[name="'+id+'-'+esc(q.id||i)+'"]:checked');if(x&&Number(x.value)===Number(q.answer))n++});return n}
'''
s = s[:start] + fn + s[end:]

old_diag = "const n=score(diag,'diag');localStorage.setItem(key,JSON.stringify({version:1,target:g,score:n,total:diag.length,completedAt:new Date().toISOString()}));location.reload()"
new_diag = "const n=grade(diag,'diag','diagResult');localStorage.setItem(key,JSON.stringify({version:1,target:g,score:n,total:diag.length,completedAt:new Date().toISOString()}));$('diagBtn').disabled=true"
if old_diag in s:
    s = s.replace(old_diag, new_diag, 1)

old_practice = "$('practiceBtn').onclick=()=>{$('practiceResult').innerHTML='<div class=\"result\">النتيجة: '+score(practice,'practiceQuiz')+' / '+practice.length+'</div>'}"
new_practice = "$('practiceBtn').onclick=()=>{grade(practice,'practiceQuiz','practiceResult');$('practiceBtn').disabled=true}"
if old_practice in s:
    s = s.replace(old_practice, new_practice, 1)

old_final = "$('finalBtn').onclick=()=>{$('finalResult').innerHTML='<div class=\"result\">النتيجة: '+score(fin,'finalQuiz')+' / '+fin.length+'</div>'}"
new_final = "$('finalBtn').onclick=()=>{grade(fin,'finalQuiz','finalResult');$('finalBtn').disabled=true}"
if old_final in s:
    s = s.replace(old_final, new_final, 1)

p.write_text(s, encoding='utf-8')
print('Annual revision: comprehensive question-specific feedback engine applied')