(function(){
  const dict={
    ar:{home:'الرئيسية',student:'الطالب',courses:'المسارات',grade8:'الصف الثاني الإعدادي',library:'المكتبة',settings:'الإعدادات',language:'لغة العرض',arabic:'العربية',french:'Français',english:'English',tagline:'منصة تعليم الفرنسية بذكاء ومتعة',homeTitle:'تعلّم الفرنسية بطريقة أذكى',homeSub:'منصة تعليمية متكاملة تجمع المناهج المدرسية ومسارات اللغة الدولية والتعلّم التفاعلي.',studentArea:'منطقة الطالب',schoolCurriculum:'المناهج المدرسية',languageTracks:'مستويات اللغة',libraryTitle:'المكتبة التعليمية',assessment:'التقييم والاختبارات',start:'ابدأ التعلم',open:'فتح',explore:'استكشف',continue:'متابعة',footer:'HM Academy © 2026'},
    fr:{home:'Accueil',student:'Élève',courses:'Parcours',grade8:'2e année préparatoire',library:'Bibliothèque',settings:'Paramètres',language:"Langue d’affichage",arabic:'العربية',french:'Français',english:'English',tagline:"Plateforme d’apprentissage du français, intelligente et motivante",homeTitle:'Apprenez le français plus intelligemment',homeSub:'Une plateforme complète réunissant les programmes scolaires, les parcours internationaux et l’apprentissage interactif.',studentArea:'Espace élève',schoolCurriculum:'Programmes scolaires',languageTracks:'Parcours de langue',libraryTitle:'Bibliothèque pédagogique',assessment:'Évaluations et tests',start:'Commencer',open:'Ouvrir',explore:'Explorer',continue:'Continuer',footer:'HM Academy © 2026'},
    en:{home:'Home',student:'Student',courses:'Learning Paths',grade8:'Grade 8',library:'Library',settings:'Settings',language:'Display language',arabic:'العربية',french:'Français',english:'English',tagline:'A smarter, more engaging French learning platform',homeTitle:'Learn French the smarter way',homeSub:'An integrated learning platform combining school curricula, international language pathways, and interactive learning.',studentArea:'Student Area',schoolCurriculum:'School Curricula',languageTracks:'Language Pathways',libraryTitle:'Learning Library',assessment:'Assessment & Tests',start:'Start Learning',open:'Open',explore:'Explore',continue:'Continue',footer:'HM Academy © 2026'}
  };
  const saved=localStorage.getItem('hm_display_language')||'ar';
  function apply(lang){lang=dict[lang]?lang:'ar';localStorage.setItem('hm_display_language',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.dataset.language=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[lang][k]!=null)el.textContent=dict[lang][k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(dict[lang][k]!=null)el.placeholder=dict[lang][k]});document.querySelectorAll('[data-lang-select]').forEach(s=>s.value=lang);window.dispatchEvent(new CustomEvent('hm:languagechange',{detail:{lang}}));}
  function mount(){document.querySelectorAll('[data-lang-select]').forEach(s=>{s.addEventListener('change',()=>apply(s.value));s.value=saved});apply(saved)}
  window.HMLanguage={dict,apply,get:()=>localStorage.getItem('hm_display_language')||'ar'};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
