from pathlib import Path
import re
p=Path('grade7-lesson-studio.html')
s=p.read_text(encoding='utf-8')
def block(section,next_section,replacement):
    global s
    pat=rf"if\(currentSection==='({section})'\).*?(?=if\(currentSection==='({next_section})'\))"
    s,n=re.subn(pat,replacement,s,count=1,flags=re.S)
    if n != 1: raise SystemExit(f'Could not restore {section}')
block('introduction','vocabulary',"if(currentSection==='introduction'){if(id!=='grade7-u1-l1')return `<div class=\"card source\"><h2>🚀 بداية الدرس</h2><p>${esc(data.titleAr||'')}</p><div class=\"section-lead\"><b>${esc(data.titleFr||'')}</b><br>${esc(jc.introduction?.goal||data.goal||'ابدأ بالتعرف على التحيات الفرنسية واختيار التحية المناسبة حسب الموقف والوقت.')}</div>${sections().length?'<h3>مكونات الدرس</h3>'+list(sections().map(x=>x.title)):''}</div>`;return `<div class=\"card source\"><h2>🚀 بداية الدرس</h2><p>${esc(data.titleAr||'')}</p><p>${esc(jc.introduction?.goal||cfg.introduction?.goal||data.goal||'التعرف على موضوع الدرس ومحتواه.')}</p>${sections().length?'<h3>مكونات المصدر</h3>'+list(sections().map(x=>x.title)):''}</div>`}")
block('video','games',"if(currentSection==='video'){if(id!=='grade7-u1-l1')return `<div class=\"card source\"><h2>🎬 الفيديو</h2><div class=\"section-lead\"><b>Vidéo complémentaire — الفيديو التكميلي</b><br>هذا الدرس يحتوي على قسم فيديو تكميلي في المصدر. سيتم عرضه فقط عند توفر ملف الفيديو/المسار الأصلي الموثق.</div><div class=\"note\">المسار الأصلي المسجل للمصدر: ${esc(data.sourceAssets?.interactive||data.sourceFiles?.interactive||'Leçon_2/lesson2_interactive.html')}</div></div>`;return `<div class=\"card source\"><h2>🎬 الفيديو</h2><div class=\"ok\">الفيديو مرتبط بالمصدر: ${esc(data.sourceFiles?.interactive||cfg.video?.source||'غير محدد')}.</div></div>`}")
block('grammar','conversation',"if(currentSection==='grammar'){if(id!=='grade7-u1-l1')return grammarEnabled()?`<div class=\"card enrich\"><h2>📘 القواعد</h2>${list(jc.grammar?.notes)}</div>`:'<div class=\"notice\"><b>لا يوجد محور قواعد مستقل في هذا الدرس.</b></div>';let trans=[['Un pyjama','بيجاما'],['Un pantalon','بنطلون'],['Un taxi','تاكسي'],['Un téléphone','تليفون'],['Une guitare','جيتار'],['Une télévision','تليفزيون']];return `<div class=\"card enrich\"><h2>📘 القاعدة اللغوية في هذا الدرس</h2><div class=\"section-lead\"><b>Les mots transparents — الكلمات الشفافة</b><br>هي كلمات فرنسية يسهل على المتعلم التعرف عليها لأن شكلها أو أصلها قريب من كلمة يعرفها في لغته.</div><div class=\"concept-grid\"><div class=\"concept\"><b>🎯 لماذا نتعلمها؟</b><br>لتكوين رصيد سريع من الكلمات التي يمكن للطالب فهمها والتعرف عليها من أول لقاء.</div><div class=\"concept\"><b>🔎 ماذا ألاحظ؟</b><br>أقارن شكل الكلمة بالمعنى الذي أعرفه، ثم أستمع إلى نطقها الفرنسي الصحيح.</div><div class=\"concept\"><b>🗣️ قاعدة مهمة</b><br>تشابه الكتابة لا يعني أن النطق متطابق؛ لذلك نقرأ الكلمة ونستمع إليها معًا.</div></div><h3>أمثلة حقيقية من الدرس</h3>${list(trans)}</div>`}")
block('conversation','practice',"if(currentSection==='conversation'){if(id!=='grade7-u1-l1'){let c=conversationItems();return `<div class=\"card source\"><h2>💬 المحادثة</h2>${c.length?list(c):'<div class=\"notice\">لا يوجد حوار مستقل في هذا الدرس.</div>'}</div>`}return `<div class=\"card source\"><h2>💬 التطبيق الشفهي</h2><div class=\"section-lead\">لا يحتوي المصدر على حوار مستقل، لذلك نحول عناصر الدرس نفسها إلى تدريب شفهي.</div></div>`}")
block('practice','video',"if(currentSection==='practice'){if(id!=='grade7-u1-l1'){let pp=practiceItems();return `<div class=\"card source\"><h2>✍️ التدريب</h2>${list(pp)}</div>`}let qs=Array.isArray(data.embeddedPractice)?data.embeddedPractice:[];return `<div class=\"card source\"><h2>✍️ التدريب</h2>${list(qs.map(q=>q.q))}</div>`}")
block('games','smart-review',"if(currentSection==='games'){if(id!=='grade7-u1-l1')return `<div class=\"card enrich\"><h2>🎮 مركز الألعاب</h2>${list(jc.games||cfg.games?.games)}</div>`;return `<div class=\"card enrich\"><h2>🎮 مركز الألعاب</h2>${list(jc.games||cfg.games?.games)}</div>`}")
block('smart-review','assessment',"if(currentSection==='smart-review'){if(id!=='grade7-u1-l1')return `<div class=\"card enrich\"><h2>🧠 المراجعة الذكية</h2>${list(jc.smartReview?.targets)}</div>`;return `<div class=\"card enrich\"><h2>🧠 المراجعة الذكية</h2>${list(jc.smartReview?.targets)}</div>`}")
block('assessment','progress',"if(currentSection==='assessment'){let a=data.formalAssessment;return `<div class=\"card source\"><h2>🏆 التقييم</h2>${a?`<div class=\"ok\">إجمالي الأسئلة المعلن في المصدر: <b>${esc(a.sourceDeclaredTotal)}</b></div>${list((a.sourceExerciseStructure||[]).map(x=>x.title))}`:'<div class=\"notice\">التقييم الخاص بهذا الدرس غير متاح حاليًا.</div>'}</div>`}")
p.write_text(s,encoding='utf-8')
