const LESSONS={
  1:{title:'الفرنسية من حولنا',goal:'اكتشف أين تظهر الفرنسية حولك ولماذا يستحق تعلمها.',steps:['لاحظ كلمات فرنسية مألوفة','اربط الكلمة الفرنسية بما تعرفه','جرّب نطقها في جملة قصيرة']},
  2:{title:'الحروف والأصوات',goal:'ابدأ قراءة الفرنسية بعين وأذن جديدتين.',steps:['لاحظ شكل الحرف','اسمع صوته','قارن بين الكتابة والنطق']},
  3:{title:'النطق والاستماع',goal:'درّب أذنك على التقاط الصوت قبل محاولة إنتاجه.',steps:['استمع أولًا','لاحظ الجزء غير المنطوق','كرر الكلمة كاملة']},
  4:{title:'أول تواصل',goal:'استخدم أول مجموعة من العبارات في موقف حقيقي.',steps:['ابدأ بالتحية','اسأل سؤالًا بسيطًا','قدّم نفسك']},
  5:{title:'بناء الجملة الأولى',goal:'حوّل القوالب الأساسية إلى جمل تستطيع استخدامها.',steps:['اختر القالب','أكمل المعلومة','قل الجملة بصوتك']},
  6:{title:'مفردات الحياة اليومية',goal:'ابنِ رصيدًا صغيرًا عالي الاستخدام بدل حفظ قائمة طويلة.',steps:['اسمع الكلمة','اربطها بمعناها','استخدمها في سياق']},
  7:{title:'جرعة قواعد تأسيسية',goal:'افهم اللبنات التي ستقابلها في بداية المرحلة الثانوية.',steps:['لاحظ الضمير','افهم وظيفة الفعل','طبّق في جملة']},
  8:{title:'مواقف وتحديات',goal:'اجمع ما تعلمته في تواصل قصير ثم اختبر جاهزيتك.',steps:['افهم الموقف','استمع','اختر الاستجابة المناسبة']}
};
function speak(text){const t=String(text||'').trim();if(!t||!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')return;const s=window.speechSynthesis;let tries=0;const play=()=>{tries++;try{s.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.82;u.pitch=1;const voices=s.getVoices();const v=voices.find(x=>String(x.lang).toLowerCase()==='fr-fr')||voices.find(x=>String(x.lang).toLowerCase().startsWith('fr'));if(v)u.voice=v;u.onerror=()=>{if(tries<3)setTimeout(play,120)};try{s.resume()}catch(_){ }s.speak(u)}catch(_){if(tries<3)setTimeout(play,120)}};play()}
function lessonNumber(){const m=document.body.innerText.match(/الدرس\s+(\d+)\s+من\s+8/);return m?Number(m[1]):0}
function addLearningLayer(n){if(!n||!LESSONS[n])return;const lesson=document.querySelector('.lesson');if(!lesson||lesson.querySelector('.course-progress'))return;const d=LESSONS[n];const pct=Math.round((n/8)*100);const progress=document.createElement('div');progress.innerHTML=`<div class="progress-label"><span>تقدمك في الكورس</span><span>${n} / 8</span></div><div class="course-progress"><span style="width:${pct}%"></span></div>`;lesson.prepend(progress);const box=document.createElement('section');box.className='enhancement';box.innerHTML=`<div><span class="tag">اكتشف قبل أن تحفظ</span><h3>هدف المحطة</h3><p>${d.goal}</p></div><div class="objective"><strong>خريطة التعلم</strong><ul>${d.steps.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;const firstH2=lesson.querySelector('h2');if(firstH2)firstH2.before(box);const done=document.createElement('div');done.className='completion';done.innerHTML='💡 <strong>قاعدة HM Academy:</strong> لا تحفظ الإجابة فقط؛ حاول أن تشرح لنفسك لماذا هي صحيحة.';lesson.appendChild(done);}
function markProgress(n){if(!n)return;try{const key='hm-secondary-starter-progress';const old=Number(localStorage.getItem(key)||0);if(n>old)localStorage.setItem(key,String(n))}catch(_){} }
document.addEventListener('click',e=>{const b=e.target.closest('[data-say]');if(b){e.preventDefault();speak(b.dataset.say)}});
document.querySelectorAll('.quiz').forEach(q=>{const ans=String(q.dataset.answer||'').trim();q.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const f=q.querySelector('.feedback');if(!f)return;const selected=b.dataset.answer||b.textContent.trim();const ok=selected===ans;f.className='feedback '+(ok?'correct':'wrong');f.textContent=ok?'✓ إجابة صحيحة — أحسنت، انتقل للخطوة التالية.':'✗ ليست الإجابة الصحيحة — لاحظ المثال ثم حاول مرة أخرى.'}))});
const n=lessonNumber();addLearningLayer(n);markProgress(n);
